### ISSUE TITLE
Milestone 2 tasks

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-java#12]
In this milestone, we focus on cleaning up existing code and make it ready for OpenSearch development

- [x] Remove X-Pack and non oss features/tests
- [x] Update namespace
- [x] Updates license headers
- [x] Remove docs
- [ ] Remove commits not related to >7.10 from *main* branch
- [ ] Update CI to run with  *OpenDistro* docker image with out security plugin

**Comment by AmiStrn** [comment]
Do we intend to change also the types of searches not supported by opensearch that exist in the client? i.e. `combined_fields` search?

**Comment by VachaShah** [comment]
@VijayanB do you think we can close this if all the tasks are addressed?
